const images = [
{src:"images/Baroque/image00001.jpg", style:"Baroque", artist:"Adriaen Brouwer", title:"Father S Of Unpleasant Duties", year:"1631"},
{src:"images/Baroque/image00002.jpg", style:"Baroque", artist:"Gian Lorenzo Bernini", title:"St Longinus", year:""},
{src:"images/Baroque/image00003.jpg", style:"Baroque", artist:"Theodoor Van Thulden", title:"Odysseus Lands At Beach Of Hades", year:""},
{src:"images/Baroque/image00004.jpg", style:"Baroque", artist:"Paul Bril", title:"Landscape With Mercury And Argus", year:"1606"},
{src:"images/Baroque/image00005.jpg", style:"Baroque", artist:"Gabriel Metsu", title:"Washerwoman", year:""},
{src:"images/Baroque/image00006.jpg", style:"Baroque", artist:"Diego Velazquez", title:"Portrait Of A Little Girl", year:""},
{src:"images/Baroque/image00007.jpg", style:"Baroque", artist:"Antoine Pesne", title:"Portrait Of A Man", year:""},
{src:"images/Baroque/image00008.jpg", style:"Baroque", artist:"Francesco Guardi", title:"Pope Pius Vi Blessing The People On Campo Santi Giovanni E Paolo", year:""},
{src:"images/Baroque/image00009.jpg", style:"Baroque", artist:"Joshua Reynolds", title:"Paul Henry Ourry", year:""},
{src:"images/Baroque/image00010.jpg", style:"Baroque", artist:"Frans Snyders", title:"Sable Of The Fox And The Heron", year:""},
{src:"images/Baroque/image00011.jpg", style:"Baroque", artist:"Francesco Guardi", title:"The Lagoon From The Fondamenta Nuove", year:""},
{src:"images/Baroque/image00012.jpg", style:"Baroque", artist:"Peter Paul Rubens", title:"Queen Tomyris With The Head Of Cyrus", year:""},
{src:"images/Baroque/image00013.jpg", style:"Baroque", artist:"Gerard Terborch", title:"Lady At Her Toilette", year:""},
{src:"images/Baroque/image00014.jpg", style:"Baroque", artist:"Adriaen Brouwer", title:"Dune Landscape By Moonlight", year:""},
{src:"images/Baroque/image00015.jpg", style:"Baroque", artist:"Diego Velazquez", title:"Portrait Of Infante Don Carlos", year:"1627"},
{src:"images/Baroque/image00016.jpg", style:"Baroque", artist:"Rembrandt", title:"Bust Of An Old Woman Rembrandt S Mother", year:"1628"},
{src:"images/Baroque/image00017.jpg", style:"Baroque", artist:"Anthony Van Dyck", title:"Lucas Vorsterman", year:""},
{src:"images/Baroque/image00018.jpg", style:"Baroque", artist:"Rembrandt", title:"Jacob Caressing Benjamin", year:"1637"},
{src:"images/Baroque/image00019.jpg", style:"Baroque", artist:"Bartolome Esteban Murillo", title:"The Good Shepherd Child", year:""},
{src:"images/Baroque/image00020.jpg", style:"Baroque", artist:"Peter Paul Rubens", title:"Diana And Callisto", year:""},
{src:"images/Early_Renaissance/image00021.jpg", style:"Early_Renaissance", artist:"Domenico Ghirlandaio", title:"St Jerome", year:"1480"},
{src:"images/Early_Renaissance/image00022.jpg", style:"Early_Renaissance", artist:"Jacopo Bellini", title:"Dormition Of The Virgin", year:""},
{src:"images/Early_Renaissance/image00023.jpg", style:"Early_Renaissance", artist:"Andrea Mantegna", title:"The Flagellation Of Christ In The Pavement", year:"1475"},
{src:"images/Early_Renaissance/image00024.jpg", style:"Early_Renaissance", artist:"Leonardo Da Vinci", title:"Head Of An Old Man", year:""},
{src:"images/Early_Renaissance/image00025.jpg", style:"Early_Renaissance", artist:"Carlo Crivelli", title:"Triptych Of Camerino", year:"1482"},
{src:"images/Early_Renaissance/image00026.jpg", style:"Early_Renaissance", artist:"Domenico Ghirlandaio", title:"St John The Evangelist On The Island Of Patmos", year:"1485"},
{src:"images/Early_Renaissance/image00027.jpg", style:"Early_Renaissance", artist:"Sandro Botticelli", title:"The Madonna And Child With The Infant Saint John The Baptist", year:""},
{src:"images/Early_Renaissance/image00028.jpg", style:"Early_Renaissance", artist:"Masaccio", title:"Portrait Of A Young Woman", year:"1425"},
{src:"images/Early_Renaissance/image00029.jpg", style:"Early_Renaissance", artist:"Antonello Da Messina", title:"St Jerome In His Study", year:""},
{src:"images/Early_Renaissance/image00030.jpg", style:"Early_Renaissance", artist:"Filippo Lippi", title:"Portrait Of A Woman", year:"1440"},
{src:"images/Early_Renaissance/image00031.jpg", style:"Early_Renaissance", artist:"Domenico Ghirlandaio", title:"Angel Appearing To Zacharias", year:"1490"},
{src:"images/Early_Renaissance/image00032.jpg", style:"Early_Renaissance", artist:"Benozzo Gozzoli", title:"St Augustine Departing For Milan Detail", year:"1465"},
{src:"images/Early_Renaissance/image00033.jpg", style:"Early_Renaissance", artist:"Filippo Lippi", title:"Meeting Of Joachim And Anne At The Golden Gate", year:""},
{src:"images/Early_Renaissance/image00034.jpg", style:"Early_Renaissance", artist:"Andrea Mantegna", title:"Scenes From The Life Of St Christopher", year:"1448"},
{src:"images/Early_Renaissance/image00035.jpg", style:"Early_Renaissance", artist:"Sandro Botticelli", title:"Giuliano De Medici", year:"1478"},
{src:"images/Early_Renaissance/image00036.jpg", style:"Early_Renaissance", artist:"Antonello Da Messina", title:"Madonna And Child Salting Madonna", year:""},
{src:"images/Early_Renaissance/image00037.jpg", style:"Early_Renaissance", artist:"Fra Angelico", title:"Saint Cosmas And Saint Damian Condamned", year:"1440"},
{src:"images/Early_Renaissance/image00038.jpg", style:"Early_Renaissance", artist:"Carlo Crivelli", title:"Saint John The Evangelist", year:""},
{src:"images/Early_Renaissance/image00039.jpg", style:"Early_Renaissance", artist:"Filippo Lippi", title:"The Vision Of St Augustine", year:"1465"},
{src:"images/Early_Renaissance/image00040.jpg", style:"Early_Renaissance", artist:"Antonello Da Messina", title:"Polyptych With St Gregory", year:"1473"},
{src:"images/High_Renaissance/image00041.jpg", style:"High_Renaissance", artist:"Andrea Mantegna", title:"Soldiers", year:""},
{src:"images/High_Renaissance/image00042.jpg", style:"High_Renaissance", artist:"Michelangelo", title:"Nude Woman On Her Knees", year:""},
{src:"images/High_Renaissance/image00043.jpg", style:"High_Renaissance", artist:"Leonardo Da Vinci", title:"Head Of St John The Evangelist", year:""},
{src:"images/High_Renaissance/image00044.jpg", style:"High_Renaissance", artist:"Andrea Mantegna", title:"Saint Jerome Reading With The Lion", year:"1500"},
{src:"images/High_Renaissance/image00045.jpg", style:"High_Renaissance", artist:"Michelangelo", title:"Annunciation Study", year:"1547"},
{src:"images/High_Renaissance/image00046.jpg", style:"High_Renaissance", artist:"Titian", title:"The Tribute Money", year:"1516"},
{src:"images/High_Renaissance/image00047.jpg", style:"High_Renaissance", artist:"Pietro Perugino", title:"Combat Of Love And Chastity", year:"1505"},
{src:"images/High_Renaissance/image00048.jpg", style:"High_Renaissance", artist:"Giorgione", title:"Arithmetic", year:"1510"},
{src:"images/High_Renaissance/image00049.jpg", style:"High_Renaissance", artist:"Luca Signorelli", title:"The Last Judgment The Right Part Of The Composition The Damned Consigned To Hell", year:"1502"},
{src:"images/High_Renaissance/image00050.jpg", style:"High_Renaissance", artist:"Vittore Carpaccio", title:"Portrait Of A Young Woman", year:""},
{src:"images/High_Renaissance/image00051.jpg", style:"High_Renaissance", artist:"Raphael", title:"St Margaret", year:"1518"},
{src:"images/High_Renaissance/image00052.jpg", style:"High_Renaissance", artist:"Raphael", title:"Justice From The Stanza Della Segnatura", year:"1511"},
{src:"images/High_Renaissance/image00053.jpg", style:"High_Renaissance", artist:"Andrea Del Sarto", title:"Stories Of Joseph", year:""},
{src:"images/High_Renaissance/image00054.jpg", style:"High_Renaissance", artist:"Andrea Del Sarto", title:"The Miracle Of The Relics Of San Filippo From The Life Of San Filippo Benizzi", year:""},
{src:"images/High_Renaissance/image00055.jpg", style:"High_Renaissance", artist:"Pietro Perugino", title:"Altarpiece Of St Augustine Adoration Of The Shepherds Detail Altarpiece Of St Augustine", year:"1510"},
{src:"images/High_Renaissance/image00056.jpg", style:"High_Renaissance", artist:"Vittore Carpaccio", title:"Presentation In The Temple", year:"1510"},
{src:"images/High_Renaissance/image00057.jpg", style:"High_Renaissance", artist:"Leonardo Da Vinci", title:"Study Of Horses", year:""},
{src:"images/High_Renaissance/image00058.jpg", style:"High_Renaissance", artist:"Giovanni Bellini", title:"The Feast Of The Gods", year:"1514"},
{src:"images/High_Renaissance/image00059.jpg", style:"High_Renaissance", artist:"Titian", title:"Portrait Of Ippolito De Medici In A Hungarian Costume", year:"1533"},
{src:"images/High_Renaissance/image00060.jpg", style:"High_Renaissance", artist:"Giorgione", title:"Portrait Of A Young Woman Laura", year:"1506"},
{src:"images/Mannerism_Late_Renaissance/image00061.jpg", style:"Mannerism_Late_Renaissance", artist:"Giuseppe Arcimboldo", title:"The Lawyer", year:"1566"},
{src:"images/Mannerism_Late_Renaissance/image00062.jpg", style:"Mannerism_Late_Renaissance", artist:"Paolo Veronese", title:"St Jerome", year:""},
{src:"images/Mannerism_Late_Renaissance/image00063.jpg", style:"Mannerism_Late_Renaissance", artist:"Agnolo Bronzino", title:"Venus Cupido And Satyr", year:""},
{src:"images/Mannerism_Late_Renaissance/image00064.jpg", style:"Mannerism_Late_Renaissance", artist:"Paolo Veronese", title:"Jesus Among The Doctors", year:"1558"},
{src:"images/Mannerism_Late_Renaissance/image00065.jpg", style:"Mannerism_Late_Renaissance", artist:"Titian", title:"St Jerome", year:"1560"},
{src:"images/Mannerism_Late_Renaissance/image00066.jpg", style:"Mannerism_Late_Renaissance", artist:"Paolo Veronese", title:"Saint Barnabas Healing The Sick", year:"1566"},
{src:"images/Mannerism_Late_Renaissance/image00067.jpg", style:"Mannerism_Late_Renaissance", artist:"Paolo Veronese", title:"Girl In The Doorway", year:"1561"},
{src:"images/Mannerism_Late_Renaissance/image00068.jpg", style:"Mannerism_Late_Renaissance", artist:"Jacopo Pontormo", title:"Portrait Of A Goldsmith", year:""},
{src:"images/Mannerism_Late_Renaissance/image00069.jpg", style:"Mannerism_Late_Renaissance", artist:"Parmigianino", title:"Helmet Shaped Like Lion", year:""},
{src:"images/Mannerism_Late_Renaissance/image00070.jpg", style:"Mannerism_Late_Renaissance", artist:"El Greco", title:"St John The Evangelist", year:""},
{src:"images/Mannerism_Late_Renaissance/image00071.jpg", style:"Mannerism_Late_Renaissance", artist:"Correggio", title:"Leda And The Swan", year:"1532"},
{src:"images/Mannerism_Late_Renaissance/image00072.jpg", style:"Mannerism_Late_Renaissance", artist:"Paolo Veronese", title:"Adoration Of The Shepherds", year:""},
{src:"images/Mannerism_Late_Renaissance/image00073.jpg", style:"Mannerism_Late_Renaissance", artist:"Gregorio Lopes", title:"Adora O Dos Pastores", year:"1544"},
{src:"images/Mannerism_Late_Renaissance/image00074.jpg", style:"Mannerism_Late_Renaissance", artist:"El Greco", title:"Christ On The Cross With Two Maries And St John", year:"1588"},
{src:"images/Mannerism_Late_Renaissance/image00075.jpg", style:"Mannerism_Late_Renaissance", artist:"Hans Von Aachen", title:"Allegory Of Peace Art And Abundance", year:"1602"},
{src:"images/Mannerism_Late_Renaissance/image00076.jpg", style:"Mannerism_Late_Renaissance", artist:"Tintoretto", title:"Birth Of St John The Baptist", year:""},
{src:"images/Mannerism_Late_Renaissance/image00077.jpg", style:"Mannerism_Late_Renaissance", artist:"El Greco", title:"St James The Less", year:""},
{src:"images/Mannerism_Late_Renaissance/image00078.jpg", style:"Mannerism_Late_Renaissance", artist:"Tintoretto", title:"Portrait Of Procurator Antonio Cappello", year:""},
{src:"images/Mannerism_Late_Renaissance/image00079.jpg", style:"Mannerism_Late_Renaissance", artist:"Titian", title:"Pieta", year:"1576"},
{src:"images/Mannerism_Late_Renaissance/image00080.jpg", style:"Mannerism_Late_Renaissance", artist:"Tintoretto", title:"The Last Judgment", year:"1562"},
{src:"images/Northern_Renaissance/image00081.jpg", style:"Northern_Renaissance", artist:"Albrecht Altdorfer", title:"The Battle Of Issus Fragment", year:"1529"},
{src:"images/Northern_Renaissance/image00082.jpg", style:"Northern_Renaissance", artist:"Albrecht Durer", title:"Arrest Of Christ", year:""},
{src:"images/Northern_Renaissance/image00083.jpg", style:"Northern_Renaissance", artist:"Joachim Wtewael", title:"Kitchen Scene", year:"1605"},
{src:"images/Northern_Renaissance/image00084.jpg", style:"Northern_Renaissance", artist:"Lucas Cranach The Elder", title:"Lamentation", year:"1538"},
{src:"images/Northern_Renaissance/image00085.jpg", style:"Northern_Renaissance", artist:"Pieter Bruegel The Elder", title:"Seascape With A View Of Antwerp", year:""},
{src:"images/Northern_Renaissance/image00086.jpg", style:"Northern_Renaissance", artist:"Hans Holbein The Younger", title:"Portrait Of Mary Wotton Lady Guildenford", year:"1527"},
{src:"images/Northern_Renaissance/image00087.jpg", style:"Northern_Renaissance", artist:"Hans Holbein The Younger", title:"Mrs Pemberton", year:""},
{src:"images/Northern_Renaissance/image00088.jpg", style:"Northern_Renaissance", artist:"Hieronymus Bosch", title:"Hermit Saints Triptych Right Panel", year:""},
{src:"images/Northern_Renaissance/image00089.jpg", style:"Northern_Renaissance", artist:"Hieronymus Bosch", title:"Allegory Of Gluttony And Lust", year:"1500"},
{src:"images/Northern_Renaissance/image00090.jpg", style:"Northern_Renaissance", artist:"Albrecht Durer", title:"Sylvan Men With Heraldic Shields", year:"1499"},
{src:"images/Northern_Renaissance/image00091.jpg", style:"Northern_Renaissance", artist:"Albrecht Durer", title:"Portrait Of Lucas Cranach The Elder", year:""},
{src:"images/Northern_Renaissance/image00092.jpg", style:"Northern_Renaissance", artist:"Hieronymus Bosch", title:"Triptych Of Temptation Of St Anthony", year:"1506"},
{src:"images/Northern_Renaissance/image00093.jpg", style:"Northern_Renaissance", artist:"Albrecht Durer", title:"Pattern From The Series Of Six Knots", year:"1507"},
{src:"images/Northern_Renaissance/image00094.jpg", style:"Northern_Renaissance", artist:"Hans Memling", title:"Hell", year:""},
{src:"images/Northern_Renaissance/image00095.jpg", style:"Northern_Renaissance", artist:"Albrecht Durer", title:"Flagellation", year:""},
{src:"images/Northern_Renaissance/image00096.jpg", style:"Northern_Renaissance", artist:"Albrecht Durer", title:"The Dead Christ With The Crown Of Thorns", year:""},
{src:"images/Northern_Renaissance/image00097.jpg", style:"Northern_Renaissance", artist:"Jean Hey", title:"The Dauphin Charles Orlant", year:"1494"},
{src:"images/Northern_Renaissance/image00098.jpg", style:"Northern_Renaissance", artist:"Joachim Wtewael", title:"Cephalus And Procris The Death Of Procris", year:"1600"},
{src:"images/Northern_Renaissance/image00099.jpg", style:"Northern_Renaissance", artist:"Mabuse", title:"Venus And The Mirror", year:""},
{src:"images/Northern_Renaissance/image00100.jpg", style:"Northern_Renaissance", artist:"Gerard David", title:"Altar Of Archangel Michael", year:""},
{src:"images/Rococo/image00101.jpg", style:"Rococo", artist:"Dmitry Levitzky", title:"Alexander I As A Child", year:"1787"},
{src:"images/Rococo/image00102.jpg", style:"Rococo", artist:"Antoine Watteau", title:"The Halt During The Chase", year:""},
{src:"images/Rococo/image00103.jpg", style:"Rococo", artist:"Louise Elisabeth Vigee Le Brun", title:"German Opera Singer Elisabeth Mara", year:""},
{src:"images/Rococo/image00104.jpg", style:"Rococo", artist:"Maurice Quentin De La Tour", title:"The Marshal De Belle Isle", year:""},
{src:"images/Rococo/image00105.jpg", style:"Rococo", artist:"Thomas Gainsborough", title:"Homecoming", year:""},
{src:"images/Rococo/image00106.jpg", style:"Rococo", artist:"Giovanni Domenico Tiepolo", title:"Preaching Of John The Baptist", year:""},
{src:"images/Rococo/image00107.jpg", style:"Rococo", artist:"Carl Ludwig Johann Christineck", title:"Portrait Of Count Orlov Chesmensky", year:"1779"},
{src:"images/Rococo/image00108.jpg", style:"Rococo", artist:"Bernardo Bellotto", title:"The Imperial Summer Residence Courtyard", year:"1758"},
{src:"images/Rococo/image00109.jpg", style:"Rococo", artist:"William Hogarth", title:"The Enraged Musician", year:"1741"},
{src:"images/Rococo/image00110.jpg", style:"Rococo", artist:"Vladimir Borovikovsky", title:"Portrait Of A And V Gagarin", year:"1802"},
{src:"images/Rococo/image00111.jpg", style:"Rococo", artist:"Maurice Quentin De La Tour", title:"Antoine Gaspard Grimold De La Reyniere", year:""},
{src:"images/Rococo/image00112.jpg", style:"Rococo", artist:"Thomas Gainsborough", title:"Landscape With Cattle", year:""},
{src:"images/Rococo/image00113.jpg", style:"Rococo", artist:"Joshua Reynolds", title:"Mrs Joseph Martin And Her Son Charles", year:"1760"},
{src:"images/Rococo/image00114.jpg", style:"Rococo", artist:"Jean Baptiste Simeon Chardin", title:"Still Life Of Cooking Utensils Cauldron Frying Pan And Eggs", year:""},
{src:"images/Rococo/image00115.jpg", style:"Rococo", artist:"Antoine Watteau", title:"Gilles", year:""},
{src:"images/Rococo/image00116.jpg", style:"Rococo", artist:"Thomas Gainsborough", title:"Benjamin Truman", year:""},
{src:"images/Rococo/image00117.jpg", style:"Rococo", artist:"Dmitry Levitzky", title:"Russian General Mikhail Krechetnikov", year:"1778"},
{src:"images/Rococo/image00118.jpg", style:"Rococo", artist:"Allan Ramsay", title:"Nude Study Of A Striding Man With Stone Sling", year:""},
{src:"images/Rococo/image00119.jpg", style:"Rococo", artist:"John Russell", title:"Anthony Knowles", year:"1801"},
{src:"images/Rococo/image00120.jpg", style:"Rococo", artist:"Dmitry Levitzky", title:"Princess Vorontsova Dashkova", year:"1784"}
];